# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Habit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Habit

  target 'HabitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HabitUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Masonry', '~> 1.1.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15.1'
pod 'LYSKit', '~> 0.0.6'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'IQKeyboardManager', '~> 6.1.1'
end
